name: Victor

options:
  bundleIdPrefix: com.victor
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  Down:
    url: https://github.com/johnxnguyen/Down.git
    from: 0.11.0
  Yams:
    url: https://github.com/jpsim/Yams.git
    from: 5.0.0
  TOMLKit:
    url: https://github.com/LebJe/TOMLKit.git
    from: 0.5.0

targets:
  Victor:
    type: application
    platform: macOS
    sources:
      - path: Victor
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Victor/Assets.xcassets
      - path: Victor/Resources
    entitlements:
      path: Victor/Victor.entitlements
    dependencies:
      - package: Down
      - package: Yams
      - package: TOMLKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.victor.Victor
        DEVELOPMENT_TEAM: 55V96YBUQ4
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Victor/Victor.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Victor
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

  VictorTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: VictorTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Victor
      - package: TOMLKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.victor.VictorTests
        DEVELOPMENT_TEAM: 55V96YBUQ4
        GENERATE_INFOPLIST_FILE: YES

schemes:
  Victor:
    build:
      targets:
        Victor: all
        VictorTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - VictorTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
